{
  description = "Bonfire — a WebGL start page that follows the Noctalia colour scheme";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system:
        f nixpkgs.legacyPackages.${system});
    in
    {
      # The static site itself. Just the files, no build step.
      packages = forAllSystems (pkgs: {
        default = self.packages.${pkgs.system}.bonfire;

        bonfire = pkgs.stdenvNoCC.mkDerivation {
          pname = "bonfire";
          version = "0.1.0";
          src = ./.;

          dontBuild = true;
          dontConfigure = true;

          installPhase = ''
            mkdir -p $out
            cp -r index.html style.css main.js shaders $out/
          '';

          meta = with pkgs.lib; {
            description = "WebGL start page themed from Noctalia";
            platforms = platforms.linux;
          };
        };
      });

      # Import this in home-manager: bonfire.homeManagerModules.default
      homeManagerModules.default = import ./module.nix self;

      devShells = forAllSystems (pkgs: {
		      default = pkgs.mkShell {
		      packages = [ pkgs.live-server ];
		      shellHook = ''
		      # colors.css is generated by Noctalia into the runtime dir; link it
		      # in so the dev server sees the same live-updating palette.
		      target="$HOME/.local/share/bonfire/colors.css"
		      if [ -e "$target" ] && [ ! -e colors.css ]; then
		      ln -s "$target" colors.css
		      echo "linked colors.css -> $target"
		      elif [ ! -e "$target" ]; then
		      echo "warning: $target missing — run 'noctalia msg templates-apply'"
		      fi
		      '';
		      };
		      });
    };
}
