#!/usr/bin/env bash

set -euo pipefail

# --- Variables ---

BONFIRE_DOWNLOAD="https://github.com/HonKLam/bonfire/releases/latest/download"
PORT=8420

BF_DIR="$HOME/.local/share/bonfire"
DH_BIN_DIR="$BF_DIR/bin"
NOCTALIA_DIR="$HOME/.config/noctalia"
TEMPLATE_DIR="$NOCTALIA_DIR/templates"
UNIT_DIR="$HOME/.config/systemd/user"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

STAGE="$(mktemp -d)"

trap 'rm -rf "$STAGE"' EXIT
die() { echo "error: $*" >&2; exit 1; }

# --- Preflight ---

# Don't run as root or sudo

if [[ $EUID -eq 0 ]]; then
	die "please don't run this with sudo"
fi

# systemd exists

# Loop to precheck all necessary commands, trigger die when any of these fail
for cmd in curl sha256sum systemctl; do
	command -v "$cmd" >/dev/null 2>&1 || die "$cmd is required but not installed"
done

# Check if Noctalia is installed
[ -d "$TEMPLATE_DIR" ] || die "$TEMPLATE_DIR could not be found -- is noctalia installed?"

# Stop our own service before the port check, so reinstalling over a running
# bonfire isn't mistaken for a port conflict.
systemctl --user stop bonfire.service 2>/dev/null || true

# port free?
if (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null;
then
	die "port $PORT is already in use"
fi


# --- Locate or fetch darkhttpd ---

# is it in PATH already?
if command -v darkhttpd >/dev/null 2>&1; then
	DARKHTTPD_PATH="$(command -v darkhttpd)"
	echo "darkhttpd found at $DARKHTTPD_PATH, using this"

# is an executable installed through bonfire already?
elif [[ -x "$DH_BIN_DIR/darkhttpd" ]]; then
	DARKHTTPD_PATH="$DH_BIN_DIR/darkhttpd"
	echo "bonfire darkhttpd installed previously, using this"

# if none of these triggered, download binary from github release
else
	echo "downloading the darkhttpd binary from the bonfire release"
	DARKHTTPD_PATH="$DH_BIN_DIR/darkhttpd"

	# Map uname -m onto the names used in the release assets, and fail loudly on
	# anything we don't publish a binary for (yet)
	case "$(uname -m)" in
		(x86_64|amd64) ARCH="x86_64" ;;
		(*) die "no prebuilt darkhttpd for $(uname -m); install darkhttpd from your package manager first" ;;
	esac

	curl -fsSL -o "$STAGE/darkhttpd-$ARCH" "$BONFIRE_DOWNLOAD/darkhttpd-$ARCH"
	curl -fsSL -o "$STAGE/darkhttpd-LICENSE" "$BONFIRE_DOWNLOAD/darkhttpd-LICENSE"
	curl -fsSL -o "$STAGE/SHA256SUMS" "$BONFIRE_DOWNLOAD/SHA256SUMS"

	# Verify Download
	(cd "$STAGE" && grep " darkhttpd-$ARCH\$" SHA256SUMS | sha256sum -c -) || die "checksum verfication failed, probably the download got corrupted?"

	mkdir -p "$DH_BIN_DIR"
	install -m 755 "$STAGE/darkhttpd-$ARCH" "$DH_BIN_DIR/darkhttpd"
	install -m 644 "$STAGE/darkhttpd-LICENSE" "$DH_BIN_DIR/darkhttpd-LICENSE"
fi


# --- Install the static files ---

mkdir -p "$BF_DIR"

# Cleanup first
find "$BF_DIR" -mindepth 1 -maxdepth 1 ! -name colors.css ! -name bin -exec rm -rf {} +

cp -r "$SCRIPT_DIR/src/." "$BF_DIR/"

# colors.css is generated by noctalia; never clobber an existing one.
if [[ -f "$BF_DIR/colors.css" ]]; then
	rm -f "$BF_DIR/colors.default.css"
else
	mv "$BF_DIR/colors.default.css" "$BF_DIR/colors.css"
fi

cp "$SCRIPT_DIR/templates/bonfire.css" "$TEMPLATE_DIR/bonfire.css"

# --- register noctalia template ---

# I do not like to mess with peoples noctalia config, i would rather tell them to add the user template manually

# --- systemd user service ---

mkdir -p "$UNIT_DIR"
cat >"$UNIT_DIR/bonfire.service" <<EOF
[Unit]
Description=bonfire start page
After=graphical-session.target

[Service]
ExecStart=$DARKHTTPD_PATH $BF_DIR --addr 127.0.0.1 --port $PORT --no-listing
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now bonfire.service

echo "bonfire installed on http://127.0.0.1:$PORT"
echo "For Noctalia Theming to work, please add the following to your noctalia/config.toml:"
echo "
[theme.templates.user.bonfire]
input_path = \"$TEMPLATE_DIR/bonfire.css\"
output_path = \"$BF_DIR/colors.css\"
"

echo "Refresh by changing wallpaper and everything should work :)"
