#!/usr/bin/env bash

set -euo pipefail

# --- Variables ---

BONFIRE_DOWNLOAD="https://github.com/HonKLam/bonfire/releases/latest/download"
PORT=8420

BF_DIR="$HOME/.local/share/bonfire"
DH_BIN_DIR="$BF_DIR/bin"
NOCTALIA_DIR="$HOME/.config/noctalia"
NOCTALIA_TEMPLATE_DIR="$NOCTALIA_DIR/templates"
MATUGEN_DIR="$HOME/.config/matugen"
MATUGEN_TEMPLATE_DIR="$MATUGEN_DIR/templates"
UNIT_DIR="$HOME/.config/systemd/user"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

STAGE="$(mktemp -d)"

trap 'rm -rf "$STAGE"' EXIT
die() { echo "error: $*" >&2; exit 1; }

usage() {
	cat <<'EOF'
usage: install.sh [--backend noctalia|matugen]

  --backend  which theming tool renders the palette. Without it, the backend
             is detected from your config; you are only asked when both (or
             neither) are present.
EOF
}

# --- Arguments ---

BACKEND=""

while [[ $# -gt 0 ]]; do
	case "$1" in
		(--backend) BACKEND="${2:-}"; shift 2 ;;
		(--backend=*) BACKEND="${1#*=}"; shift ;;
		(-h|--help) usage; exit 0 ;;
		(*) usage >&2; die "unknown argument: $1" ;;
	esac
done

case "$BACKEND" in
	(""|noctalia|matugen) ;;
	(*) die "unknown backend '$BACKEND' -- expected noctalia or matugen" ;;
esac

# --- Preflight ---

# Don't run as root or sudo

if [[ $EUID -eq 0 ]]; then
	die "please don't run this with sudo"
fi

# systemd exists

# Loop to precheck all necessary commands, trigger die when any of these fail
for cmd in curl sha256sum systemctl; do
	command -v "$cmd" >/dev/null 2>&1 || die "$cmd is required but not installed"
done

# --- Pick a backend ---

# An explicit --backend is taken at face value: you may well drive matugen with
# --config from somewhere we would never think to look.
if [[ -z "$BACKEND" ]]; then
	has_noctalia=false
	has_matugen=false

	[[ -d "$NOCTALIA_TEMPLATE_DIR" ]] && has_noctalia=true
	# matugen keeps no config directory until it first runs, so accept the
	# binary being on PATH as evidence too.
	{ [[ -d "$MATUGEN_DIR" ]] || command -v matugen >/dev/null 2>&1; } && has_matugen=true

	if $has_noctalia && $has_matugen; then
		[[ -t 0 ]] || die "found both noctalia and matugen -- rerun with --backend noctalia or --backend matugen"

		echo "found both noctalia and matugen"
		while [[ -z "$BACKEND" ]]; do
			read -r -p "which backend should render the palette? [noctalia/matugen]: " reply
			case "$reply" in
				(noctalia|n) BACKEND="noctalia" ;;
				(matugen|m) BACKEND="matugen" ;;
				(*) echo "please answer noctalia or matugen" ;;
			esac
		done
	elif $has_noctalia; then
		BACKEND="noctalia"
	elif $has_matugen; then
		BACKEND="matugen"
	else
		die "found neither $NOCTALIA_TEMPLATE_DIR nor matugen -- is either of them installed?"
	fi
fi

case "$BACKEND" in
	(noctalia) TEMPLATE_DIR="$NOCTALIA_TEMPLATE_DIR" ;;
	(matugen)  TEMPLATE_DIR="$MATUGEN_TEMPLATE_DIR" ;;
esac

echo "using the $BACKEND backend"

# Stop our own service before the port check, so reinstalling over a running
# bonfire isn't mistaken for a port conflict.
systemctl --user stop bonfire.service 2>/dev/null || true

# port free?
if (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null;
then
	die "port $PORT is already in use"
fi


# --- Locate or fetch darkhttpd ---

# is it in PATH already?
if command -v darkhttpd >/dev/null 2>&1; then
	DARKHTTPD_PATH="$(command -v darkhttpd)"
	echo "darkhttpd found at $DARKHTTPD_PATH, using this"

# is an executable installed through bonfire already?
elif [[ -x "$DH_BIN_DIR/darkhttpd" ]]; then
	DARKHTTPD_PATH="$DH_BIN_DIR/darkhttpd"
	echo "bonfire darkhttpd installed previously, using this"

# if none of these triggered, download binary from github release
else
	echo "downloading the darkhttpd binary from the bonfire release"
	DARKHTTPD_PATH="$DH_BIN_DIR/darkhttpd"

	# Map uname -m onto the names used in the release assets, and fail loudly on
	# anything we don't publish a binary for (yet)
	case "$(uname -m)" in
		(x86_64|amd64) ARCH="x86_64" ;;
		(*) die "no prebuilt darkhttpd for $(uname -m); install darkhttpd from your package manager first" ;;
	esac

	curl -fsSL -o "$STAGE/darkhttpd-$ARCH" "$BONFIRE_DOWNLOAD/darkhttpd-$ARCH"
	curl -fsSL -o "$STAGE/darkhttpd-LICENSE" "$BONFIRE_DOWNLOAD/darkhttpd-LICENSE"
	curl -fsSL -o "$STAGE/SHA256SUMS" "$BONFIRE_DOWNLOAD/SHA256SUMS"

	# Verify Download
	(cd "$STAGE" && grep " darkhttpd-$ARCH\$" SHA256SUMS | sha256sum -c -) || die "checksum verfication failed, probably the download got corrupted?"

	mkdir -p "$DH_BIN_DIR"
	install -m 755 "$STAGE/darkhttpd-$ARCH" "$DH_BIN_DIR/darkhttpd"
	install -m 644 "$STAGE/darkhttpd-LICENSE" "$DH_BIN_DIR/darkhttpd-LICENSE"
fi


# --- Install the static files ---

mkdir -p "$BF_DIR"

# Cleanup first
find "$BF_DIR" -mindepth 1 -maxdepth 1 ! -name colors.css ! -name bin -exec rm -rf {} +

cp -r "$SCRIPT_DIR/src/." "$BF_DIR/"

# colors.css is generated by the backend; never clobber an existing one.
if [[ -f "$BF_DIR/colors.css" ]]; then
	rm -f "$BF_DIR/colors.default.css"
else
	mv "$BF_DIR/colors.default.css" "$BF_DIR/colors.css"
fi

# The template is the same file for both backends -- noctalia uses matugen's
# placeholder syntax -- only the directory it belongs in differs.
mkdir -p "$TEMPLATE_DIR"
cp "$SCRIPT_DIR/templates/bonfire.css" "$TEMPLATE_DIR/bonfire.css"

# --- register the template ---

# I do not like to mess with peoples config, i would rather tell them to add the user template manually

# --- systemd user service ---

mkdir -p "$UNIT_DIR"
cat >"$UNIT_DIR/bonfire.service" <<EOF
[Unit]
Description=bonfire start page
After=graphical-session.target

[Service]
ExecStart=$DARKHTTPD_PATH $BF_DIR --addr 127.0.0.1 --port $PORT --no-listing
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now bonfire.service

echo "bonfire installed on http://127.0.0.1:$PORT"

if [[ "$BACKEND" == "noctalia" ]]; then
	echo "For Noctalia theming to work, please add the following to your noctalia/config.toml:"
	echo "
[theme.templates.user.bonfire]
input_path = \"$TEMPLATE_DIR/bonfire.css\"
output_path = \"$BF_DIR/colors.css\"
"
	echo "Refresh by changing wallpaper and everything should work :)"
else
	echo "For matugen theming to work, please add the following to your matugen/config.toml:"
	echo "
[templates.bonfire]
input_path = \"$TEMPLATE_DIR/bonfire.css\"
output_path = \"$BF_DIR/colors.css\"
"
	echo "Then re-run matugen (e.g. 'matugen image /path/to/your/wallpaper') and everything should work :)"
fi
